#############################################################################
# Makefile for building: pgXplorer
# Generated by qmake (2.01a) (Qt 4.8.0) on: Fri Dec 30 20:07:26 2011
# Project:  pgXplorer.pro
# Template: app
# Command: /usr/bin/qmake -spec /usr/share/qt/mkspecs/unsupported/linux-clang CONFIG+=debug CONFIG+=declarative_debug -o Makefile pgXplorer.pro
#############################################################################

####### Compiler, tools and options

CC            = clang
CXX           = clang++
DEFINES       = -DQT_SQL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt/mkspecs/unsupported/linux-clang -I. -I/usr/include/QtCore -I/usr/include/QtGui -I/usr/include/QtSql -I/usr/include -I.
LINK          = clang++
LFLAGS        = -Wl,-O1,--sort-common,--as-needed,-z,relro,--hash-style=gnu -ccc-gcc-name g++
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtSql -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		tableLink.cpp \
		schemaLink.cpp \
		database.cpp \
		schema.cpp \
		table.cpp \
		mainWin.cpp \
		pgxconsole.cpp \
		queryview.cpp \
		tableview.cpp \
		connectionproperties.cpp \
		pgxeditor.cpp \
		function.cpp \
		functionlink.cpp \
		view.cpp \
		highlighter.cpp \
		licensedialog.cpp \
		querymodel.cpp moc_database.cpp \
		moc_schema.cpp \
		moc_table.cpp \
		moc_mainWin.cpp \
		moc_pgxconsole.cpp \
		moc_queryview.cpp \
		moc_tableview.cpp \
		moc_connectionproperties.cpp \
		moc_pgxeditor.cpp \
		moc_function.cpp \
		moc_view.cpp \
		moc_highlighter.cpp \
		moc_licensedialog.cpp \
		moc_querymodel.cpp \
		qrc_pgXplorer.cpp
OBJECTS       = main.o \
		tableLink.o \
		schemaLink.o \
		database.o \
		schema.o \
		table.o \
		mainWin.o \
		pgxconsole.o \
		queryview.o \
		tableview.o \
		connectionproperties.o \
		pgxeditor.o \
		function.o \
		functionlink.o \
		view.o \
		highlighter.o \
		licensedialog.o \
		querymodel.o \
		moc_database.o \
		moc_schema.o \
		moc_table.o \
		moc_mainWin.o \
		moc_pgxconsole.o \
		moc_queryview.o \
		moc_tableview.o \
		moc_connectionproperties.o \
		moc_pgxeditor.o \
		moc_function.o \
		moc_view.o \
		moc_highlighter.o \
		moc_licensedialog.o \
		moc_querymodel.o \
		qrc_pgXplorer.o
DIST          = /usr/share/qt/mkspecs/common/unix.conf \
		/usr/share/qt/mkspecs/common/linux.conf \
		/usr/share/qt/mkspecs/common/gcc-base.conf \
		/usr/share/qt/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt/mkspecs/common/clang.conf \
		/usr/share/qt/mkspecs/qconfig.pri \
		/usr/share/qt/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt/mkspecs/features/qt_functions.prf \
		/usr/share/qt/mkspecs/features/qt_config.prf \
		/usr/share/qt/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt/mkspecs/features/default_pre.prf \
		/usr/share/qt/mkspecs/features/debug.prf \
		/usr/share/qt/mkspecs/features/default_post.prf \
		/usr/share/qt/mkspecs/features/warn_on.prf \
		/usr/share/qt/mkspecs/features/qt.prf \
		/usr/share/qt/mkspecs/features/unix/thread.prf \
		/usr/share/qt/mkspecs/features/moc.prf \
		/usr/share/qt/mkspecs/features/declarative_debug.prf \
		/usr/share/qt/mkspecs/features/resources.prf \
		/usr/share/qt/mkspecs/features/uic.prf \
		/usr/share/qt/mkspecs/features/yacc.prf \
		/usr/share/qt/mkspecs/features/lex.prf \
		/usr/share/qt/mkspecs/features/include_source_dir.prf \
		pgXplorer.pro
QMAKE_TARGET  = pgXplorer
DESTDIR       = 
TARGET        = pgXplorer

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: pgXplorer.pro  /usr/share/qt/mkspecs/unsupported/linux-clang/qmake.conf /usr/share/qt/mkspecs/common/unix.conf \
		/usr/share/qt/mkspecs/common/linux.conf \
		/usr/share/qt/mkspecs/common/gcc-base.conf \
		/usr/share/qt/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt/mkspecs/common/clang.conf \
		/usr/share/qt/mkspecs/qconfig.pri \
		/usr/share/qt/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt/mkspecs/features/qt_functions.prf \
		/usr/share/qt/mkspecs/features/qt_config.prf \
		/usr/share/qt/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt/mkspecs/features/default_pre.prf \
		/usr/share/qt/mkspecs/features/debug.prf \
		/usr/share/qt/mkspecs/features/default_post.prf \
		/usr/share/qt/mkspecs/features/warn_on.prf \
		/usr/share/qt/mkspecs/features/qt.prf \
		/usr/share/qt/mkspecs/features/unix/thread.prf \
		/usr/share/qt/mkspecs/features/moc.prf \
		/usr/share/qt/mkspecs/features/declarative_debug.prf \
		/usr/share/qt/mkspecs/features/resources.prf \
		/usr/share/qt/mkspecs/features/uic.prf \
		/usr/share/qt/mkspecs/features/yacc.prf \
		/usr/share/qt/mkspecs/features/lex.prf \
		/usr/share/qt/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtSql.prl \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt/mkspecs/unsupported/linux-clang CONFIG+=debug CONFIG+=declarative_debug -o Makefile pgXplorer.pro
/usr/share/qt/mkspecs/common/unix.conf:
/usr/share/qt/mkspecs/common/linux.conf:
/usr/share/qt/mkspecs/common/gcc-base.conf:
/usr/share/qt/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt/mkspecs/common/clang.conf:
/usr/share/qt/mkspecs/qconfig.pri:
/usr/share/qt/mkspecs/modules/qt_phonon.pri:
/usr/share/qt/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt/mkspecs/features/qt_functions.prf:
/usr/share/qt/mkspecs/features/qt_config.prf:
/usr/share/qt/mkspecs/features/exclusive_builds.prf:
/usr/share/qt/mkspecs/features/default_pre.prf:
/usr/share/qt/mkspecs/features/debug.prf:
/usr/share/qt/mkspecs/features/default_post.prf:
/usr/share/qt/mkspecs/features/warn_on.prf:
/usr/share/qt/mkspecs/features/qt.prf:
/usr/share/qt/mkspecs/features/unix/thread.prf:
/usr/share/qt/mkspecs/features/moc.prf:
/usr/share/qt/mkspecs/features/declarative_debug.prf:
/usr/share/qt/mkspecs/features/resources.prf:
/usr/share/qt/mkspecs/features/uic.prf:
/usr/share/qt/mkspecs/features/yacc.prf:
/usr/share/qt/mkspecs/features/lex.prf:
/usr/share/qt/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtSql.prl:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt/mkspecs/unsupported/linux-clang CONFIG+=debug CONFIG+=declarative_debug -o Makefile pgXplorer.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/pgXplorer1.0.0 || $(MKDIR) .tmp/pgXplorer1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/pgXplorer1.0.0/ && $(COPY_FILE) --parents tableLink.h schemaLink.h database.h schema.h table.h mainWin.h pgxconsole.h queryview.h tableview.h connectionproperties.h pgxeditor.h function.h functionlink.h view.h highlighter.h licensedialog.h querymodel.h .tmp/pgXplorer1.0.0/ && $(COPY_FILE) --parents pgXplorer.qrc .tmp/pgXplorer1.0.0/ && $(COPY_FILE) --parents main.cpp tableLink.cpp schemaLink.cpp database.cpp schema.cpp table.cpp mainWin.cpp pgxconsole.cpp queryview.cpp tableview.cpp connectionproperties.cpp pgxeditor.cpp function.cpp functionlink.cpp view.cpp highlighter.cpp licensedialog.cpp querymodel.cpp .tmp/pgXplorer1.0.0/ && $(COPY_FILE) --parents pgXplorer_ja.ts pgXplorer_fr.ts .tmp/pgXplorer1.0.0/ && (cd `dirname .tmp/pgXplorer1.0.0` && $(TAR) pgXplorer1.0.0.tar pgXplorer1.0.0 && $(COMPRESS) pgXplorer1.0.0.tar) && $(MOVE) `dirname .tmp/pgXplorer1.0.0`/pgXplorer1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/pgXplorer1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_database.cpp moc_schema.cpp moc_table.cpp moc_mainWin.cpp moc_pgxconsole.cpp moc_queryview.cpp moc_tableview.cpp moc_connectionproperties.cpp moc_pgxeditor.cpp moc_function.cpp moc_view.cpp moc_highlighter.cpp moc_licensedialog.cpp moc_querymodel.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_database.cpp moc_schema.cpp moc_table.cpp moc_mainWin.cpp moc_pgxconsole.cpp moc_queryview.cpp moc_tableview.cpp moc_connectionproperties.cpp moc_pgxeditor.cpp moc_function.cpp moc_view.cpp moc_highlighter.cpp moc_licensedialog.cpp moc_querymodel.cpp
moc_database.cpp: mainWin.h \
		schema.h \
		schemaLink.h \
		tableLink.h \
		view.h \
		database.h \
		table.h \
		function.h \
		functionlink.h \
		database.h
	/usr/bin/moc $(DEFINES) $(INCPATH) database.h -o moc_database.cpp

moc_schema.cpp: mainWin.h \
		schemaLink.h \
		tableLink.h \
		view.h \
		database.h \
		schema.h \
		functionlink.h \
		table.h \
		function.h \
		schema.h
	/usr/bin/moc $(DEFINES) $(INCPATH) schema.h -o moc_schema.cpp

moc_table.cpp: database.h \
		mainWin.h \
		schema.h \
		schemaLink.h \
		tableLink.h \
		view.h \
		functionlink.h \
		table.h \
		function.h \
		table.h
	/usr/bin/moc $(DEFINES) $(INCPATH) table.h -o moc_table.cpp

moc_mainWin.cpp: mainWin.h
	/usr/bin/moc $(DEFINES) $(INCPATH) mainWin.h -o moc_mainWin.cpp

moc_pgxconsole.cpp: database.h \
		mainWin.h \
		schema.h \
		schemaLink.h \
		tableLink.h \
		view.h \
		functionlink.h \
		table.h \
		function.h \
		highlighter.h \
		pgxconsole.h
	/usr/bin/moc $(DEFINES) $(INCPATH) pgxconsole.h -o moc_pgxconsole.cpp

moc_queryview.cpp: pgxconsole.h \
		database.h \
		mainWin.h \
		schema.h \
		schemaLink.h \
		tableLink.h \
		view.h \
		functionlink.h \
		table.h \
		function.h \
		highlighter.h \
		querymodel.h \
		queryview.h
	/usr/bin/moc $(DEFINES) $(INCPATH) queryview.h -o moc_queryview.cpp

moc_tableview.cpp: database.h \
		mainWin.h \
		schema.h \
		schemaLink.h \
		tableLink.h \
		view.h \
		functionlink.h \
		table.h \
		function.h \
		tableview.h
	/usr/bin/moc $(DEFINES) $(INCPATH) tableview.h -o moc_tableview.cpp

moc_connectionproperties.cpp: database.h \
		mainWin.h \
		schema.h \
		schemaLink.h \
		tableLink.h \
		view.h \
		functionlink.h \
		table.h \
		function.h \
		connectionproperties.h
	/usr/bin/moc $(DEFINES) $(INCPATH) connectionproperties.h -o moc_connectionproperties.cpp

moc_pgxeditor.cpp: database.h \
		mainWin.h \
		schema.h \
		schemaLink.h \
		tableLink.h \
		view.h \
		functionlink.h \
		table.h \
		function.h \
		highlighter.h \
		pgxeditor.h
	/usr/bin/moc $(DEFINES) $(INCPATH) pgxeditor.h -o moc_pgxeditor.cpp

moc_function.cpp: database.h \
		mainWin.h \
		schema.h \
		schemaLink.h \
		tableLink.h \
		view.h \
		functionlink.h \
		table.h \
		function.h \
		function.h
	/usr/bin/moc $(DEFINES) $(INCPATH) function.h -o moc_function.cpp

moc_view.cpp: database.h \
		mainWin.h \
		schema.h \
		schemaLink.h \
		tableLink.h \
		view.h \
		functionlink.h \
		table.h \
		function.h \
		view.h
	/usr/bin/moc $(DEFINES) $(INCPATH) view.h -o moc_view.cpp

moc_highlighter.cpp: highlighter.h
	/usr/bin/moc $(DEFINES) $(INCPATH) highlighter.h -o moc_highlighter.cpp

moc_licensedialog.cpp: database.h \
		mainWin.h \
		schema.h \
		schemaLink.h \
		tableLink.h \
		view.h \
		functionlink.h \
		table.h \
		function.h \
		licensedialog.h
	/usr/bin/moc $(DEFINES) $(INCPATH) licensedialog.h -o moc_licensedialog.cpp

moc_querymodel.cpp: querymodel.h
	/usr/bin/moc $(DEFINES) $(INCPATH) querymodel.h -o moc_querymodel.cpp

compiler_rcc_make_all: qrc_pgXplorer.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_pgXplorer.cpp
qrc_pgXplorer.cpp: pgXplorer.qrc \
		pgXplorer.ico
	/usr/bin/rcc -name pgXplorer pgXplorer.qrc -o qrc_pgXplorer.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

main.o: main.cpp mainWin.h \
		licensedialog.h \
		database.h \
		schema.h \
		schemaLink.h \
		tableLink.h \
		view.h \
		functionlink.h \
		table.h \
		function.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

tableLink.o: tableLink.cpp tableLink.h \
		schema.h \
		mainWin.h \
		schemaLink.h \
		view.h \
		database.h \
		table.h \
		function.h \
		functionlink.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tableLink.o tableLink.cpp

schemaLink.o: schemaLink.cpp schemaLink.h \
		database.h \
		mainWin.h \
		schema.h \
		tableLink.h \
		view.h \
		functionlink.h \
		table.h \
		function.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o schemaLink.o schemaLink.cpp

database.o: database.cpp database.h \
		mainWin.h \
		schema.h \
		schemaLink.h \
		tableLink.h \
		view.h \
		functionlink.h \
		table.h \
		function.h \
		connectionproperties.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o database.o database.cpp

schema.o: schema.cpp schema.h \
		mainWin.h \
		schemaLink.h \
		tableLink.h \
		view.h \
		database.h \
		table.h \
		function.h \
		functionlink.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o schema.o schema.cpp

table.o: table.cpp mainWin.h \
		database.h \
		schema.h \
		schemaLink.h \
		tableLink.h \
		view.h \
		functionlink.h \
		table.h \
		function.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o table.o table.cpp

mainWin.o: mainWin.cpp database.h \
		mainWin.h \
		schema.h \
		schemaLink.h \
		tableLink.h \
		view.h \
		functionlink.h \
		table.h \
		function.h \
		tableview.h \
		queryview.h \
		pgxconsole.h \
		highlighter.h \
		querymodel.h \
		connectionproperties.h \
		pgxeditor.h \
		licensedialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainWin.o mainWin.cpp

pgxconsole.o: pgxconsole.cpp pgxconsole.h \
		database.h \
		mainWin.h \
		schema.h \
		schemaLink.h \
		tableLink.h \
		view.h \
		functionlink.h \
		table.h \
		function.h \
		highlighter.h \
		queryview.h \
		querymodel.h \
		explainview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pgxconsole.o pgxconsole.cpp

queryview.o: queryview.cpp queryview.h \
		pgxconsole.h \
		database.h \
		mainWin.h \
		schema.h \
		schemaLink.h \
		tableLink.h \
		view.h \
		functionlink.h \
		table.h \
		function.h \
		highlighter.h \
		querymodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o queryview.o queryview.cpp

tableview.o: tableview.cpp tableview.h \
		database.h \
		mainWin.h \
		schema.h \
		schemaLink.h \
		tableLink.h \
		view.h \
		functionlink.h \
		table.h \
		function.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tableview.o tableview.cpp

connectionproperties.o: connectionproperties.cpp connectionproperties.h \
		database.h \
		mainWin.h \
		schema.h \
		schemaLink.h \
		tableLink.h \
		view.h \
		functionlink.h \
		table.h \
		function.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o connectionproperties.o connectionproperties.cpp

pgxeditor.o: pgxeditor.cpp pgxeditor.h \
		database.h \
		mainWin.h \
		schema.h \
		schemaLink.h \
		tableLink.h \
		view.h \
		functionlink.h \
		table.h \
		function.h \
		highlighter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pgxeditor.o pgxeditor.cpp

function.o: function.cpp mainWin.h \
		database.h \
		schema.h \
		schemaLink.h \
		tableLink.h \
		view.h \
		functionlink.h \
		table.h \
		function.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o function.o function.cpp

functionlink.o: functionlink.cpp functionlink.h \
		schema.h \
		mainWin.h \
		schemaLink.h \
		tableLink.h \
		view.h \
		database.h \
		table.h \
		function.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o functionlink.o functionlink.cpp

view.o: view.cpp mainWin.h \
		database.h \
		schema.h \
		schemaLink.h \
		tableLink.h \
		view.h \
		functionlink.h \
		table.h \
		function.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o view.o view.cpp

highlighter.o: highlighter.cpp highlighter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o highlighter.o highlighter.cpp

licensedialog.o: licensedialog.cpp licensedialog.h \
		database.h \
		mainWin.h \
		schema.h \
		schemaLink.h \
		tableLink.h \
		view.h \
		functionlink.h \
		table.h \
		function.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o licensedialog.o licensedialog.cpp

querymodel.o: querymodel.cpp querymodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o querymodel.o querymodel.cpp

moc_database.o: moc_database.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_database.o moc_database.cpp

moc_schema.o: moc_schema.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_schema.o moc_schema.cpp

moc_table.o: moc_table.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_table.o moc_table.cpp

moc_mainWin.o: moc_mainWin.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainWin.o moc_mainWin.cpp

moc_pgxconsole.o: moc_pgxconsole.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_pgxconsole.o moc_pgxconsole.cpp

moc_queryview.o: moc_queryview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_queryview.o moc_queryview.cpp

moc_tableview.o: moc_tableview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_tableview.o moc_tableview.cpp

moc_connectionproperties.o: moc_connectionproperties.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_connectionproperties.o moc_connectionproperties.cpp

moc_pgxeditor.o: moc_pgxeditor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_pgxeditor.o moc_pgxeditor.cpp

moc_function.o: moc_function.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_function.o moc_function.cpp

moc_view.o: moc_view.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_view.o moc_view.cpp

moc_highlighter.o: moc_highlighter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_highlighter.o moc_highlighter.cpp

moc_licensedialog.o: moc_licensedialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_licensedialog.o moc_licensedialog.cpp

moc_querymodel.o: moc_querymodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_querymodel.o moc_querymodel.cpp

qrc_pgXplorer.o: qrc_pgXplorer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_pgXplorer.o qrc_pgXplorer.cpp

####### Install

install_target: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/home/cirrus/pgXplorer2/pgXplorer/C:/QtSDK/Examples/4.7/graphicsview/pgXplorer/ || $(MKDIR) $(INSTALL_ROOT)/home/cirrus/pgXplorer2/pgXplorer/C:/QtSDK/Examples/4.7/graphicsview/pgXplorer/ 
	-$(INSTALL_PROGRAM) "$(QMAKE_TARGET)" "$(INSTALL_ROOT)/home/cirrus/pgXplorer2/pgXplorer/c:/QtSDK/Examples/4.7/graphicsview/pgXplorer/$(QMAKE_TARGET)"

uninstall_target:  FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/home/cirrus/pgXplorer2/pgXplorer/c:/QtSDK/Examples/4.7/graphicsview/pgXplorer/$(QMAKE_TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/home/cirrus/pgXplorer2/pgXplorer/C:/QtSDK/Examples/4.7/graphicsview/pgXplorer/ 


install_sources: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/home/cirrus/pgXplorer2/pgXplorer/C:/QtSDK/Examples/4.7/graphicsview/pgXplorer/ || $(MKDIR) $(INSTALL_ROOT)/home/cirrus/pgXplorer2/pgXplorer/C:/QtSDK/Examples/4.7/graphicsview/pgXplorer/ 
	-$(INSTALL_FILE) /home/cirrus/pgXplorer2/pgXplorer/main.cpp $(INSTALL_ROOT)/home/cirrus/pgXplorer2/pgXplorer/C:/QtSDK/Examples/4.7/graphicsview/pgXplorer/
	-$(INSTALL_FILE) /home/cirrus/pgXplorer2/pgXplorer/tableLink.cpp $(INSTALL_ROOT)/home/cirrus/pgXplorer2/pgXplorer/C:/QtSDK/Examples/4.7/graphicsview/pgXplorer/
	-$(INSTALL_FILE) /home/cirrus/pgXplorer2/pgXplorer/schemaLink.cpp $(INSTALL_ROOT)/home/cirrus/pgXplorer2/pgXplorer/C:/QtSDK/Examples/4.7/graphicsview/pgXplorer/
	-$(INSTALL_FILE) /home/cirrus/pgXplorer2/pgXplorer/database.cpp $(INSTALL_ROOT)/home/cirrus/pgXplorer2/pgXplorer/C:/QtSDK/Examples/4.7/graphicsview/pgXplorer/
	-$(INSTALL_FILE) /home/cirrus/pgXplorer2/pgXplorer/schema.cpp $(INSTALL_ROOT)/home/cirrus/pgXplorer2/pgXplorer/C:/QtSDK/Examples/4.7/graphicsview/pgXplorer/
	-$(INSTALL_FILE) /home/cirrus/pgXplorer2/pgXplorer/table.cpp $(INSTALL_ROOT)/home/cirrus/pgXplorer2/pgXplorer/C:/QtSDK/Examples/4.7/graphicsview/pgXplorer/
	-$(INSTALL_FILE) /home/cirrus/pgXplorer2/pgXplorer/mainWin.cpp $(INSTALL_ROOT)/home/cirrus/pgXplorer2/pgXplorer/C:/QtSDK/Examples/4.7/graphicsview/pgXplorer/
	-$(INSTALL_FILE) /home/cirrus/pgXplorer2/pgXplorer/pgxconsole.cpp $(INSTALL_ROOT)/home/cirrus/pgXplorer2/pgXplorer/C:/QtSDK/Examples/4.7/graphicsview/pgXplorer/
	-$(INSTALL_FILE) /home/cirrus/pgXplorer2/pgXplorer/queryview.cpp $(INSTALL_ROOT)/home/cirrus/pgXplorer2/pgXplorer/C:/QtSDK/Examples/4.7/graphicsview/pgXplorer/
	-$(INSTALL_FILE) /home/cirrus/pgXplorer2/pgXplorer/tableview.cpp $(INSTALL_ROOT)/home/cirrus/pgXplorer2/pgXplorer/C:/QtSDK/Examples/4.7/graphicsview/pgXplorer/
	-$(INSTALL_FILE) /home/cirrus/pgXplorer2/pgXplorer/connectionproperties.cpp $(INSTALL_ROOT)/home/cirrus/pgXplorer2/pgXplorer/C:/QtSDK/Examples/4.7/graphicsview/pgXplorer/
	-$(INSTALL_FILE) /home/cirrus/pgXplorer2/pgXplorer/pgxeditor.cpp $(INSTALL_ROOT)/home/cirrus/pgXplorer2/pgXplorer/C:/QtSDK/Examples/4.7/graphicsview/pgXplorer/
	-$(INSTALL_FILE) /home/cirrus/pgXplorer2/pgXplorer/function.cpp $(INSTALL_ROOT)/home/cirrus/pgXplorer2/pgXplorer/C:/QtSDK/Examples/4.7/graphicsview/pgXplorer/
	-$(INSTALL_FILE) /home/cirrus/pgXplorer2/pgXplorer/functionlink.cpp $(INSTALL_ROOT)/home/cirrus/pgXplorer2/pgXplorer/C:/QtSDK/Examples/4.7/graphicsview/pgXplorer/
	-$(INSTALL_FILE) /home/cirrus/pgXplorer2/pgXplorer/view.cpp $(INSTALL_ROOT)/home/cirrus/pgXplorer2/pgXplorer/C:/QtSDK/Examples/4.7/graphicsview/pgXplorer/
	-$(INSTALL_FILE) /home/cirrus/pgXplorer2/pgXplorer/highlighter.cpp $(INSTALL_ROOT)/home/cirrus/pgXplorer2/pgXplorer/C:/QtSDK/Examples/4.7/graphicsview/pgXplorer/
	-$(INSTALL_FILE) /home/cirrus/pgXplorer2/pgXplorer/licensedialog.cpp $(INSTALL_ROOT)/home/cirrus/pgXplorer2/pgXplorer/C:/QtSDK/Examples/4.7/graphicsview/pgXplorer/
	-$(INSTALL_FILE) /home/cirrus/pgXplorer2/pgXplorer/querymodel.cpp $(INSTALL_ROOT)/home/cirrus/pgXplorer2/pgXplorer/C:/QtSDK/Examples/4.7/graphicsview/pgXplorer/
	-$(INSTALL_FILE) /home/cirrus/pgXplorer2/pgXplorer/tableLink.h $(INSTALL_ROOT)/home/cirrus/pgXplorer2/pgXplorer/C:/QtSDK/Examples/4.7/graphicsview/pgXplorer/
	-$(INSTALL_FILE) /home/cirrus/pgXplorer2/pgXplorer/schemaLink.h $(INSTALL_ROOT)/home/cirrus/pgXplorer2/pgXplorer/C:/QtSDK/Examples/4.7/graphicsview/pgXplorer/
	-$(INSTALL_FILE) /home/cirrus/pgXplorer2/pgXplorer/database.h $(INSTALL_ROOT)/home/cirrus/pgXplorer2/pgXplorer/C:/QtSDK/Examples/4.7/graphicsview/pgXplorer/
	-$(INSTALL_FILE) /home/cirrus/pgXplorer2/pgXplorer/schema.h $(INSTALL_ROOT)/home/cirrus/pgXplorer2/pgXplorer/C:/QtSDK/Examples/4.7/graphicsview/pgXplorer/
	-$(INSTALL_FILE) /home/cirrus/pgXplorer2/pgXplorer/table.h $(INSTALL_ROOT)/home/cirrus/pgXplorer2/pgXplorer/C:/QtSDK/Examples/4.7/graphicsview/pgXplorer/
	-$(INSTALL_FILE) /home/cirrus/pgXplorer2/pgXplorer/mainWin.h $(INSTALL_ROOT)/home/cirrus/pgXplorer2/pgXplorer/C:/QtSDK/Examples/4.7/graphicsview/pgXplorer/
	-$(INSTALL_FILE) /home/cirrus/pgXplorer2/pgXplorer/pgxconsole.h $(INSTALL_ROOT)/home/cirrus/pgXplorer2/pgXplorer/C:/QtSDK/Examples/4.7/graphicsview/pgXplorer/
	-$(INSTALL_FILE) /home/cirrus/pgXplorer2/pgXplorer/queryview.h $(INSTALL_ROOT)/home/cirrus/pgXplorer2/pgXplorer/C:/QtSDK/Examples/4.7/graphicsview/pgXplorer/
	-$(INSTALL_FILE) /home/cirrus/pgXplorer2/pgXplorer/tableview.h $(INSTALL_ROOT)/home/cirrus/pgXplorer2/pgXplorer/C:/QtSDK/Examples/4.7/graphicsview/pgXplorer/
	-$(INSTALL_FILE) /home/cirrus/pgXplorer2/pgXplorer/connectionproperties.h $(INSTALL_ROOT)/home/cirrus/pgXplorer2/pgXplorer/C:/QtSDK/Examples/4.7/graphicsview/pgXplorer/
	-$(INSTALL_FILE) /home/cirrus/pgXplorer2/pgXplorer/pgxeditor.h $(INSTALL_ROOT)/home/cirrus/pgXplorer2/pgXplorer/C:/QtSDK/Examples/4.7/graphicsview/pgXplorer/
	-$(INSTALL_FILE) /home/cirrus/pgXplorer2/pgXplorer/function.h $(INSTALL_ROOT)/home/cirrus/pgXplorer2/pgXplorer/C:/QtSDK/Examples/4.7/graphicsview/pgXplorer/
	-$(INSTALL_FILE) /home/cirrus/pgXplorer2/pgXplorer/functionlink.h $(INSTALL_ROOT)/home/cirrus/pgXplorer2/pgXplorer/C:/QtSDK/Examples/4.7/graphicsview/pgXplorer/
	-$(INSTALL_FILE) /home/cirrus/pgXplorer2/pgXplorer/view.h $(INSTALL_ROOT)/home/cirrus/pgXplorer2/pgXplorer/C:/QtSDK/Examples/4.7/graphicsview/pgXplorer/
	-$(INSTALL_FILE) /home/cirrus/pgXplorer2/pgXplorer/highlighter.h $(INSTALL_ROOT)/home/cirrus/pgXplorer2/pgXplorer/C:/QtSDK/Examples/4.7/graphicsview/pgXplorer/
	-$(INSTALL_FILE) /home/cirrus/pgXplorer2/pgXplorer/licensedialog.h $(INSTALL_ROOT)/home/cirrus/pgXplorer2/pgXplorer/C:/QtSDK/Examples/4.7/graphicsview/pgXplorer/
	-$(INSTALL_FILE) /home/cirrus/pgXplorer2/pgXplorer/querymodel.h $(INSTALL_ROOT)/home/cirrus/pgXplorer2/pgXplorer/C:/QtSDK/Examples/4.7/graphicsview/pgXplorer/
	-$(INSTALL_FILE) /home/cirrus/pgXplorer2/pgXplorer/pgXplorer.qrc $(INSTALL_ROOT)/home/cirrus/pgXplorer2/pgXplorer/C:/QtSDK/Examples/4.7/graphicsview/pgXplorer/
	-$(INSTALL_FILE) /home/cirrus/pgXplorer2/pgXplorer/pgXplorer.pro $(INSTALL_ROOT)/home/cirrus/pgXplorer2/pgXplorer/C:/QtSDK/Examples/4.7/graphicsview/pgXplorer/


uninstall_sources:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/home/cirrus/pgXplorer2/pgXplorer/C:/QtSDK/Examples/4.7/graphicsview/pgXplorer/main.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/cirrus/pgXplorer2/pgXplorer/C:/QtSDK/Examples/4.7/graphicsview/pgXplorer/tableLink.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/cirrus/pgXplorer2/pgXplorer/C:/QtSDK/Examples/4.7/graphicsview/pgXplorer/schemaLink.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/cirrus/pgXplorer2/pgXplorer/C:/QtSDK/Examples/4.7/graphicsview/pgXplorer/database.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/cirrus/pgXplorer2/pgXplorer/C:/QtSDK/Examples/4.7/graphicsview/pgXplorer/schema.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/cirrus/pgXplorer2/pgXplorer/C:/QtSDK/Examples/4.7/graphicsview/pgXplorer/table.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/cirrus/pgXplorer2/pgXplorer/C:/QtSDK/Examples/4.7/graphicsview/pgXplorer/mainWin.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/cirrus/pgXplorer2/pgXplorer/C:/QtSDK/Examples/4.7/graphicsview/pgXplorer/pgxconsole.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/cirrus/pgXplorer2/pgXplorer/C:/QtSDK/Examples/4.7/graphicsview/pgXplorer/queryview.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/cirrus/pgXplorer2/pgXplorer/C:/QtSDK/Examples/4.7/graphicsview/pgXplorer/tableview.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/cirrus/pgXplorer2/pgXplorer/C:/QtSDK/Examples/4.7/graphicsview/pgXplorer/connectionproperties.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/cirrus/pgXplorer2/pgXplorer/C:/QtSDK/Examples/4.7/graphicsview/pgXplorer/pgxeditor.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/cirrus/pgXplorer2/pgXplorer/C:/QtSDK/Examples/4.7/graphicsview/pgXplorer/function.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/cirrus/pgXplorer2/pgXplorer/C:/QtSDK/Examples/4.7/graphicsview/pgXplorer/functionlink.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/cirrus/pgXplorer2/pgXplorer/C:/QtSDK/Examples/4.7/graphicsview/pgXplorer/view.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/cirrus/pgXplorer2/pgXplorer/C:/QtSDK/Examples/4.7/graphicsview/pgXplorer/highlighter.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/cirrus/pgXplorer2/pgXplorer/C:/QtSDK/Examples/4.7/graphicsview/pgXplorer/licensedialog.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/cirrus/pgXplorer2/pgXplorer/C:/QtSDK/Examples/4.7/graphicsview/pgXplorer/querymodel.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/cirrus/pgXplorer2/pgXplorer/C:/QtSDK/Examples/4.7/graphicsview/pgXplorer/tableLink.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/cirrus/pgXplorer2/pgXplorer/C:/QtSDK/Examples/4.7/graphicsview/pgXplorer/schemaLink.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/cirrus/pgXplorer2/pgXplorer/C:/QtSDK/Examples/4.7/graphicsview/pgXplorer/database.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/cirrus/pgXplorer2/pgXplorer/C:/QtSDK/Examples/4.7/graphicsview/pgXplorer/schema.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/cirrus/pgXplorer2/pgXplorer/C:/QtSDK/Examples/4.7/graphicsview/pgXplorer/table.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/cirrus/pgXplorer2/pgXplorer/C:/QtSDK/Examples/4.7/graphicsview/pgXplorer/mainWin.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/cirrus/pgXplorer2/pgXplorer/C:/QtSDK/Examples/4.7/graphicsview/pgXplorer/pgxconsole.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/cirrus/pgXplorer2/pgXplorer/C:/QtSDK/Examples/4.7/graphicsview/pgXplorer/queryview.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/cirrus/pgXplorer2/pgXplorer/C:/QtSDK/Examples/4.7/graphicsview/pgXplorer/tableview.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/cirrus/pgXplorer2/pgXplorer/C:/QtSDK/Examples/4.7/graphicsview/pgXplorer/connectionproperties.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/cirrus/pgXplorer2/pgXplorer/C:/QtSDK/Examples/4.7/graphicsview/pgXplorer/pgxeditor.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/cirrus/pgXplorer2/pgXplorer/C:/QtSDK/Examples/4.7/graphicsview/pgXplorer/function.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/cirrus/pgXplorer2/pgXplorer/C:/QtSDK/Examples/4.7/graphicsview/pgXplorer/functionlink.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/cirrus/pgXplorer2/pgXplorer/C:/QtSDK/Examples/4.7/graphicsview/pgXplorer/view.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/cirrus/pgXplorer2/pgXplorer/C:/QtSDK/Examples/4.7/graphicsview/pgXplorer/highlighter.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/cirrus/pgXplorer2/pgXplorer/C:/QtSDK/Examples/4.7/graphicsview/pgXplorer/licensedialog.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/cirrus/pgXplorer2/pgXplorer/C:/QtSDK/Examples/4.7/graphicsview/pgXplorer/querymodel.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/cirrus/pgXplorer2/pgXplorer/C:/QtSDK/Examples/4.7/graphicsview/pgXplorer/pgXplorer.qrc 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/cirrus/pgXplorer2/pgXplorer/C:/QtSDK/Examples/4.7/graphicsview/pgXplorer/pgXplorer.pro
	-$(DEL_DIR) $(INSTALL_ROOT)/home/cirrus/pgXplorer2/pgXplorer/C:/QtSDK/Examples/4.7/graphicsview/pgXplorer/ 


install:  install_target install_sources  FORCE

uninstall: uninstall_target uninstall_sources   FORCE

FORCE:

